
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      閫傜敤浜?.NET Framework MSBuild 鐗堟湰 17.14.23+b0019275e
      鐢熸垚鍚姩鏃堕棿涓?2025/9/14 8:29:41銆?
      
      鑺傜偣 1 涓婄殑椤圭洰鈥淔:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\3.31.6-msvc6\\CompilerIdCXX\\CompilerIdCXX.vcxproj鈥?榛樿鐩爣)銆?
      PrepareForBuild:
        姝ｅ湪鍒涘缓鐩綍鈥淒ebug\\鈥濄€?
        姝ｅ湪鍒涘缓鐩綍鈥淒ebug\\CompilerIdCXX.tlog\\鈥濄€?
      InitializeBuildStatus:
        姝ｅ湪鍒涘缓鈥淒ebug\\CompilerIdCXX.tlog\\unsuccessfulbuild鈥濓紝鍥犱负宸叉寚瀹氣€淎lwaysCreate鈥濄€?
        姝ｅ湪瀵光€淒ebug\\CompilerIdCXX.tlog\\unsuccessfulbuild鈥濇墽琛?Touch 浠诲姟銆?
      ClCompile:
        d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\3.31.6-msvc6\\CompilerIdCXX\\.\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe
      FinalizeBuildStatus:
        姝ｅ湪鍒犻櫎鏂囦欢鈥淒ebug\\CompilerIdCXX.tlog\\unsuccessfulbuild鈥濄€?
        姝ｅ湪瀵光€淒ebug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate鈥濇墽琛?Touch 浠诲姟銆?
      宸插畬鎴愮敓鎴愰」鐩€淔:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\3.31.6-msvc6\\CompilerIdCXX\\CompilerIdCXX.vcxproj鈥?榛樿鐩爣)鐨勬搷浣溿€?
      
      宸叉垚鍔熺敓鎴愩€?
          0 涓鍛?
          0 涓敊璇?
      
      宸茬敤鏃堕棿 00:00:02.88
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build_static/CMakeFiles/3.31.6-msvc6/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build_static/CMakeFiles/CMakeScratch/TryCompile-ys4o0o"
      binary: "F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build_static/CMakeFiles/CMakeScratch/TryCompile-ys4o0o"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build_static/CMakeFiles/CMakeScratch/TryCompile-ys4o0o'
        
        Run Build Command(s): "d:/Program/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_762ae.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        閫傜敤浜?.NET Framework MSBuild 鐗堟湰 17.14.23+b0019275e
        鐢熸垚鍚姩鏃堕棿涓?2025/9/14 8:29:45銆?
        
        鑺傜偣 1 涓婄殑椤圭洰鈥淔:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-ys4o0o\\cmTC_762ae.vcxproj鈥?榛樿鐩爣)銆?
        PrepareForBuild:
          姝ｅ湪鍒涘缓鐩綍鈥渃mTC_762ae.dir\\Debug\\鈥濄€?
          姝ｅ湪鍒涘缓鐩綍鈥淔:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-ys4o0o\\Debug\\鈥濄€?
          姝ｅ湪鍒涘缓鐩綍鈥渃mTC_762ae.dir\\Debug\\cmTC_762ae.tlog\\鈥濄€?
        InitializeBuildStatus:
          姝ｅ湪鍒涘缓鈥渃mTC_762ae.dir\\Debug\\cmTC_762ae.tlog\\unsuccessfulbuild鈥濓紝鍥犱负宸叉寚瀹氣€淎lwaysCreate鈥濄€?
          姝ｅ湪瀵光€渃mTC_762ae.dir\\Debug\\cmTC_762ae.tlog\\unsuccessfulbuild鈥濇墽琛?Touch 浠诲姟銆?
        ClCompile:
          d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_762ae.dir\\Debug\\\\" /Fd"cmTC_762ae.dir\\Debug\\vc141.pdb" /Gd /TP /errorReport:queue "D:\\Program\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\share\\cmake-3.31\\Modules\\CMakeCXXCompilerABI.cpp"
          鐢ㄤ簬 x64 鐨?Microsoft (R) C/C++ 浼樺寲缂栬瘧鍣?19.16.27054 鐗?
          鐗堟潈鎵€鏈?C) Microsoft Corporation銆備繚鐣欐墍鏈夋潈鍒┿€?
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_762ae.dir\\Debug\\\\" /Fd"cmTC_762ae.dir\\Debug\\vc141.pdb" /Gd /TP /errorReport:queue "D:\\Program\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\share\\cmake-3.31\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
          
        Link:
          d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-ys4o0o\\Debug\\cmTC_762ae.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build_static/CMakeFiles/CMakeScratch/TryCompile-ys4o0o/Debug/cmTC_762ae.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build_static/CMakeFiles/CMakeScratch/TryCompile-ys4o0o/Debug/cmTC_762ae.lib" /MACHINE:X64  /machine:x64 cmTC_762ae.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_762ae.vcxproj -> F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-ys4o0o\\Debug\\cmTC_762ae.exe
        FinalizeBuildStatus:
          姝ｅ湪鍒犻櫎鏂囦欢鈥渃mTC_762ae.dir\\Debug\\cmTC_762ae.tlog\\unsuccessfulbuild鈥濄€?
          姝ｅ湪瀵光€渃mTC_762ae.dir\\Debug\\cmTC_762ae.tlog\\cmTC_762ae.lastbuildstate鈥濇墽琛?Touch 浠诲姟銆?
        宸插畬鎴愮敓鎴愰」鐩€淔:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-ys4o0o\\cmTC_762ae.vcxproj鈥?榛樿鐩爣)鐨勬搷浣溿€?
        
        宸叉垚鍔熺敓鎴愩€?
            0 涓鍛?
            0 涓敊璇?
        
        宸茬敤鏃堕棿 00:00:01.35
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': d:/Program/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the CXX compiler's linker: "d:/Program/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.16.27054.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CheckIncludeFileCXX.cmake:98 (try_compile)"
      - "CMakeLists.txt:11 (check_include_file_cxx)"
    checks:
      - "Looking for C++ include initializer_list"
    directories:
      source: "F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build_static/CMakeFiles/CMakeScratch/TryCompile-q8j581"
      binary: "F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build_static/CMakeFiles/CMakeScratch/TryCompile-q8j581"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MODULE_PATH: "F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/c++/cmake"
    buildResult:
      variable: "HAS_CXX14"
      cached: true
      stdout: |
        Change Dir: 'F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build_static/CMakeFiles/CMakeScratch/TryCompile-q8j581'
        
        Run Build Command(s): "d:/Program/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_6bd09.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        閫傜敤浜?.NET Framework MSBuild 鐗堟湰 17.14.23+b0019275e
        鐢熸垚鍚姩鏃堕棿涓?2025/9/14 8:29:47銆?
        
        鑺傜偣 1 涓婄殑椤圭洰鈥淔:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-q8j581\\cmTC_6bd09.vcxproj鈥?榛樿鐩爣)銆?
        PrepareForBuild:
          姝ｅ湪鍒涘缓鐩綍鈥渃mTC_6bd09.dir\\Debug\\鈥濄€?
          姝ｅ湪鍒涘缓鐩綍鈥淔:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-q8j581\\Debug\\鈥濄€?
          姝ｅ湪鍒涘缓鐩綍鈥渃mTC_6bd09.dir\\Debug\\cmTC_6bd09.tlog\\鈥濄€?
        InitializeBuildStatus:
          姝ｅ湪鍒涘缓鈥渃mTC_6bd09.dir\\Debug\\cmTC_6bd09.tlog\\unsuccessfulbuild鈥濓紝鍥犱负宸叉寚瀹氣€淎lwaysCreate鈥濄€?
          姝ｅ湪瀵光€渃mTC_6bd09.dir\\Debug\\cmTC_6bd09.tlog\\unsuccessfulbuild鈥濇墽琛?Touch 浠诲姟銆?
        ClCompile:
          d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_6bd09.dir\\Debug\\\\" /Fd"cmTC_6bd09.dir\\Debug\\vc141.pdb" /Gd /TP /errorReport:queue "F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-q8j581\\CheckIncludeFile.cxx"
          鐢ㄤ簬 x64 鐨?Microsoft (R) C/C++ 浼樺寲缂栬瘧鍣?19.16.27054 鐗?
          鐗堟潈鎵€鏈?C) Microsoft Corporation銆備繚鐣欐墍鏈夋潈鍒┿€?
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_6bd09.dir\\Debug\\\\" /Fd"cmTC_6bd09.dir\\Debug\\vc141.pdb" /Gd /TP /errorReport:queue "F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-q8j581\\CheckIncludeFile.cxx"
          CheckIncludeFile.cxx
          
        Link:
          d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-q8j581\\Debug\\cmTC_6bd09.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build_static/CMakeFiles/CMakeScratch/TryCompile-q8j581/Debug/cmTC_6bd09.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build_static/CMakeFiles/CMakeScratch/TryCompile-q8j581/Debug/cmTC_6bd09.lib" /MACHINE:X64  /machine:x64 cmTC_6bd09.dir\\Debug\\CheckIncludeFile.obj
          cmTC_6bd09.vcxproj -> F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-q8j581\\Debug\\cmTC_6bd09.exe
        FinalizeBuildStatus:
          姝ｅ湪鍒犻櫎鏂囦欢鈥渃mTC_6bd09.dir\\Debug\\cmTC_6bd09.tlog\\unsuccessfulbuild鈥濄€?
          姝ｅ湪瀵光€渃mTC_6bd09.dir\\Debug\\cmTC_6bd09.tlog\\cmTC_6bd09.lastbuildstate鈥濇墽琛?Touch 浠诲姟銆?
        宸插畬鎴愮敓鎴愰」鐩€淔:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build_static\\CMakeFiles\\CMakeScratch\\TryCompile-q8j581\\cmTC_6bd09.vcxproj鈥?榛樿鐩爣)鐨勬搷浣溿€?
        
        宸叉垚鍔熺敓鎴愩€?
            0 涓鍛?
            0 涓敊璇?
        
        宸茬敤鏃堕棿 00:00:02.73
        
      exitCode: 0
...
