
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: /MT;/EHsc
      Id flags:  
      
      The output was:
      0
      适用于 .NET Framework MSBuild 版本 17.14.23+b0019275e
      生成启动时间为 2025/9/14 23:32:32。
      
      节点 1 上的项目“F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\3.31.6-msvc6\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        正在对“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”执行 Touch 任务。
      ClCompile:
        d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\3.31.6-msvc6\\CompilerIdCXX\\.\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\3.31.6-msvc6\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.93
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build-v141/CMakeFiles/3.31.6-msvc6/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build-v141/CMakeFiles/CMakeScratch/TryCompile-dr4hai"
      binary: "F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build-v141/CMakeFiles/CMakeScratch/TryCompile-dr4hai"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/MT /EHsc"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MSVC_RUNTIME_LIBRARY: "MultiThreaded"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build-v141/CMakeFiles/CMakeScratch/TryCompile-dr4hai'
        
        Run Build Command(s): "d:/Program/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_87bcc.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        适用于 .NET Framework MSBuild 版本 17.14.23+b0019275e
        生成启动时间为 2025/9/14 23:32:33。
        
        节点 1 上的项目“F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-dr4hai\\cmTC_87bcc.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_87bcc.dir\\Debug\\”。
          正在创建目录“F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-dr4hai\\Debug\\”。
          正在创建目录“cmTC_87bcc.dir\\Debug\\cmTC_87bcc.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_87bcc.dir\\Debug\\cmTC_87bcc.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_87bcc.dir\\Debug\\cmTC_87bcc.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_87bcc.dir\\Debug\\\\" /Fd"cmTC_87bcc.dir\\Debug\\vc141.pdb" /Gd /TP /errorReport:queue "D:\\Program\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\share\\cmake-3.31\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.16.27054 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          
          cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_87bcc.dir\\Debug\\\\" /Fd"cmTC_87bcc.dir\\Debug\\vc141.pdb" /Gd /TP /errorReport:queue "D:\\Program\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\share\\cmake-3.31\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
          
        Link:
          d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-dr4hai\\Debug\\cmTC_87bcc.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build-v141/CMakeFiles/CMakeScratch/TryCompile-dr4hai/Debug/cmTC_87bcc.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build-v141/CMakeFiles/CMakeScratch/TryCompile-dr4hai/Debug/cmTC_87bcc.lib" /MACHINE:X64  /machine:x64 cmTC_87bcc.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_87bcc.vcxproj -> F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-dr4hai\\Debug\\cmTC_87bcc.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_87bcc.dir\\Debug\\cmTC_87bcc.tlog\\unsuccessfulbuild”。
          正在对“cmTC_87bcc.dir\\Debug\\cmTC_87bcc.tlog\\cmTC_87bcc.lastbuildstate”执行 Touch 任务。
        已完成生成项目“F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-dr4hai\\cmTC_87bcc.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.29
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': d:/Program/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the CXX compiler's linker: "d:/Program/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.16.27054.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Program/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CheckIncludeFileCXX.cmake:98 (try_compile)"
      - "c++/CMakeLists.txt:11 (check_include_file_cxx)"
    checks:
      - "Looking for C++ include initializer_list"
    directories:
      source: "F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build-v141/CMakeFiles/CMakeScratch/TryCompile-qolpje"
      binary: "F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build-v141/CMakeFiles/CMakeScratch/TryCompile-qolpje"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/MT /EHsc"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MODULE_PATH: "F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/c++/cmake"
      CMAKE_MSVC_RUNTIME_LIBRARY: "MultiThreaded"
    buildResult:
      variable: "HAS_CXX14"
      cached: true
      stdout: |
        Change Dir: 'F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build-v141/CMakeFiles/CMakeScratch/TryCompile-qolpje'
        
        Run Build Command(s): "d:/Program/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_c8879.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        适用于 .NET Framework MSBuild 版本 17.14.23+b0019275e
        生成启动时间为 2025/9/14 23:32:35。
        
        节点 1 上的项目“F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-qolpje\\cmTC_c8879.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_c8879.dir\\Debug\\”。
          正在创建目录“F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-qolpje\\Debug\\”。
          正在创建目录“cmTC_c8879.dir\\Debug\\cmTC_c8879.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_c8879.dir\\Debug\\cmTC_c8879.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_c8879.dir\\Debug\\cmTC_c8879.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c8879.dir\\Debug\\\\" /Fd"cmTC_c8879.dir\\Debug\\vc141.pdb" /Gd /TP /errorReport:queue "F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-qolpje\\CheckIncludeFile.cxx"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.16.27054 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          
          cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c8879.dir\\Debug\\\\" /Fd"cmTC_c8879.dir\\Debug\\vc141.pdb" /Gd /TP /errorReport:queue "F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-qolpje\\CheckIncludeFile.cxx"
          CheckIncludeFile.cxx
          
        Link:
          d:\\Program\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-qolpje\\Debug\\cmTC_c8879.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build-v141/CMakeFiles/CMakeScratch/TryCompile-qolpje/Debug/cmTC_c8879.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"F:/3.Projects/mancan_v1/weasel/librime/deps/capnproto/build-v141/CMakeFiles/CMakeScratch/TryCompile-qolpje/Debug/cmTC_c8879.lib" /MACHINE:X64  /machine:x64 cmTC_c8879.dir\\Debug\\CheckIncludeFile.obj
          cmTC_c8879.vcxproj -> F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-qolpje\\Debug\\cmTC_c8879.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_c8879.dir\\Debug\\cmTC_c8879.tlog\\unsuccessfulbuild”。
          正在对“cmTC_c8879.dir\\Debug\\cmTC_c8879.tlog\\cmTC_c8879.lastbuildstate”执行 Touch 任务。
        已完成生成项目“F:\\3.Projects\\mancan_v1\\weasel\\librime\\deps\\capnproto\\build-v141\\CMakeFiles\\CMakeScratch\\TryCompile-qolpje\\cmTC_c8879.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.27
        
      exitCode: 0
...
